package com.locationbase.Entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@Entity
@Table(name = "Planner")
@NoArgsConstructor
public class PlannerEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "planner_id")
    private int planner_id;

    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "user_id", nullable = true)
    private UserEntity user_id; // Assuming UserEntity has a `user_id` field

    @ManyToOne
    @JoinColumn(name = "theme_name", referencedColumnName = "theme_name", nullable = true)
    private ThemeEntity theme_name; // Assuming ThemeEntity has a `theme_name` field

    @Column(name = "start_date", nullable = true)
    private LocalDate start_date;


    @Column(name = "date", nullable = false)
    private LocalDate date;

    @Column(name = "landmark_name", length = 50, nullable = false)
    private String landmark_name;

    // Constructors, Getters, Setters can be auto-generated by Lombok (@Data) annotation
}
